### PR TITLE
Update correct usage of copyright for Apache Kafka

### LINKED ISSUE #106: Update correct usage of copyright for Apache Kafka
⚠️ Wait for #98  to be merged

# Description

The first occurrence of the name "Apacha Kafka" on a page always has to have a copyright (`Apache Kafka®`)

In order to help find occurrences, we added a style rule in our Vale config (`first-kafka-registered.yml`)

## Todo:

- in the Vale style config, set the level to "error" (`level: error`)

- run `npm run spell:error`

This will give you a report of errors and help you find occurrences of the wrong use in the text.

The log will show you the file where the first use of it was found without a trademark as well as the line number:
Screenshot 2023-09-28 at 13 40 23

Note:  The error will list all findings for the use of "Kafka" without the trademark. You need to add the `®` to the **first**  occurrence on the page. 

- update the usage to correct trademarking 

The `npm run spell:error` should be green before making a PR.

### PR DESCRIPTION
**Pull request by basavarajakj**
This PR will fixes #106 which Update correct usage of copyright for Apache Kafka

Fixes: #106 
### TEST

```npm run spell:error``` was green, No error, No Warnings

### CODE REVIEW

**Comment by programmiri** [comment]
Hi @Basavarajakjbasuu thanks for your PR! Could you update your branch with the current `main` and check the rule again? I'm getting more files that throw this error, it might not show up for you because there where changes in the meantime. Also we updates our pipeline to show the errors correctly.

**Comment by Basavarajakjbasuu** [comment]
Hi @programmiri  does your pipeline updated to show error in local machine? Still know I am not able to see any error

**Comment by programmiri** [comment]
>Hi @programmiri does your pipeline updated to show error in local machine? Still know I am not able to see any error

The pipeline on github is still using an outdated workflow. If you update your branch with `main` and run `npm run spell:error` you should see the errors. 

If I check out `main` right now, change the level for this rule to "error" and run  `npm run spell:error`, I get errors for these files:

```
Releases/release240.md
docs/Releases/release250.md
docs/Releases/release210.md
docs/Releases/release100.md
docs/Releases/release220.md
docs/Releases/release110.md
docs/index.md
docs/quickstart.md
docs/Concepts/metastore.md
docs/Releases/release120.md
docs/Concepts/users-teams.md
docs/HowTo/connectors/manage-connectors.md
docs/Concepts/promotion.md
docs/features.md
docs/Concepts/workflows.md
docs/HowTo/environments.md
docs/HowTo/connectors/Request-a-new-connector.md
docs/HowTo/kafka-cluster-migration/sync-acls-to-cluster.md
docs/HowTo/connectors/index.md
docs/HowTo/kafka-cluster-migration/sync-topics-from-cluster.md
docs/HowTo/settings.md
docs/HowTo/kafka-cluster-migration/sync-topics-to-cluster.md
docs/HowTo/kafka-cluster-migration/sync-connectors-from-cluster.md
docs/HowTo/kafka-cluster-migration/index.md
docs/HowTo/kafka-cluster-migration/sync-schemas-to-cluster.md
docs/HowTo/kafka-cluster-migration/sync-acls-from-cluster.md
docs/HowTo/kafka-cluster-migration/tenant-config.md
docs/HowTo/installation/index.md
docs/HowTo/installation/run-source.md
docs/HowTo/clusterconnectivity/aiven-karapace-cluster-ssl-protocol.md
docs/HowTo/clusterconnectivity/confluent-cloud-kafka-cluster-ssl-protocol.md
docs/HowTo/installation/configure-klaw-wizard.md
docs/HowTo/clusterconnectivity/kafka-cluster-sasl-ssl-protocol.md
docs/HowTo/installation/run-docker.md
docs/HowTo/clusterconnectivity/index.md
docs/HowTo/clusterconnectivity/sr-cluster-ssl-protocol.md
docs/HowTo/clusterconnectivity/kafka-cluster-ssl-protocol.md
docs/HowTo/clusterconnectivity/klaw-core-with-clusterapi.md
docs/HowTo/schemas/index.md
docs/HowTo/schemas/Promote-a-schema.md
docs/HowTo/schemas/Request-a-schema.md
docs/HowTo/subscriptions/Delete-a-subscription.md
docs/HowTo/subscriptions/Request-a-subscription.md
docs/HowTo/subscriptions/index.md
docs/HowTo/teams/manage-teams.md
docs/HowTo/topics/Edit-topic-request.md
docs/HowTo/clusters.md
docs/HowTo/topics/Delete-a-topic.md
docs/HowTo/topics/Claim-a-topic.md
docs/HowTo/topics/Topic-overview.md
docs/HowTo/topics/Request-a-new-topic.md
docs/HowTo/topics/Promote-a-topic.md
docs/HowTo/topics/index.md
blog/2023/09/schema-management-disaster-recovery-in-klaw.md
blog/2023/07/high-availability-for-klaw.md
STYLEGUIDE.md
```

**Comment by programmiri** [comment]
Hi @basavarajakj  did you have time already to check this errors again?

**Comment by programmiri** [comment]
Hi! I'm going to close this pull request and open the issue up again in case someone wants to add some contribution to hacktoberfest right before the end.

**Pull request closed without merging**
