### PR TITLE
Add linux docker cmd

### PR DESCRIPTION
**Pull request by aindriu-aiven**
Adding a new capability to toggle between the linux and windows/mac version of the docker command also updating to use the latest version of Klaw for the docker demo.

### CODE REVIEW

**Comment by aindriu-aiven** [comment]
@programmiri I added a material ui component ToggleButton let me know if this is ok or if I need some other component.

I also still need to finish testing this but first need to see how it renders on the demo site.

**Comment by aindriu-aiven** [comment]
> @programmiri I added a material ui component ToggleButton let me know if this is ok or if I need some other component.
> 
> I also still need to finish testing this but first need to see how it renders on the demo site.

Indeed the build fails because it can't find that 🤦

**Comment by programmiri** [comment]
OK, added an update: https://github.com/Aiven-Open/klaw-docs/pull/233/commits/c745e495a9d56d7531cc05c6a287853ddb37397f


#### quick explanation

- I used `Tabs` instead of buttons -> they are semantically the best choice, as it indicates to the user that there is a list of choices and selection one choice will change something about the content of this tab area. `Tabs` does not need additional  reactivity from our site, it can even be statically handled
- this enabled keyboard and screen reader usability out of the box
- I added a `section` with an `aria-label` around the `Tab`, because the component from Docusaurus offeres no way to add an accessible label to the `tablist` itself, so screenreader will first get an information about a selected `tab`, but no context for that. Section with the label does help here. 
- I added a `minHeight` to the `div` around the `CodeBlock` so the layout does not jump when switching tabs

**Comment by aindriu-aiven** [comment]
> OK, added an update: [c745e49](https://github.com/Aiven-Open/klaw-docs/commit/c745e495a9d56d7531cc05c6a287853ddb37397f)
> 
> #### quick explanation
> * I used `Tabs` instead of buttons -> they are semantically the best choice, as it indicates to the user that there is a list of choices and selection one choice will change something about the content of this tab area. `Tabs` does not need additional  reactivity from our site, it can even be statically handled
> * this enabled keyboard and screen reader usability out of the box
> * I added a `section` with an `aria-label` around the `Tab`, because the component from Docusaurus offeres no way to add an accessible label to the `tablist` itself, so screenreader will first get an information about a selected `tab`, but no context for that. Section with the label does help here.
> * I added a `minHeight` to the `div` around the `CodeBlock` so the layout does not jump when switching tabs

This is great thank you, I had started with Material tabs and then didnt want to introduce Material UI into the docs, knowing the bas tab works well here is great to know. The statis dev site has refreshed and it looks super !!!

**Comment by programmiri** [comment]
Luckily Docusaurus offers some components out of the box, so that one was nice to do :D But it's not always intuitive how to use what.

**Review by programmiri — DISMISSED** [review]

**Comment by programmiri** [comment]
I approved! I would say we should check with Harshini just to make sure the wording is clear and then it's good to go.

**Comment by harshini-rangaswamy** [comment]
> I approved! I would say we should check with Harshini just to make sure the wording is clear and then it's good to go.

It looks great! I like the tabbed approach, and the wording is good. However, the extra period needs to be removed from this [line](https://github.com/Aiven-Open/klaw-docs/blob/c745e495a9d56d7531cc05c6a287853ddb37397f/src/components/QuickStartRow/index.jsx#L79).

**Review by programmiri — APPROVED** [review]

**Pull request merged**
